language: node_js # 构建所需的语言环境
node_js:
  - "v11.14.0"  # 对应的版本
install:
- npm install
script:
- npm run build
cache:
  directories:
  - node_modules # 依赖缓存的目录
deploy:
    provider: pages
    skip_cleanup: true
    local-dir: ./vuepress/dist/
    keep_history: true
    on: 
        branch: master