install:
- npm install
script:
- npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: d0dfa78e334a5587fa723f0e057b7d974994a2bd
    local-dir: ./vuepress/dist/
    keep_history: true
    on: 
        branch: master